---
title: "Die Weggefährt*innen"
editor: visual
format:
  html:
    toc: true
---

Alle Personen, die sich in diesem Datensatz zur queeren Geschichte befinden, existierten nicht in einem Vakuum (well, anderes Wort) / alleine. Sie waren umgeben mit anderen Menschen, die sie liebten, mit denen sie zusammengearbeitet haben, von denen sie verfolgt wurden.

Durch strukturierte Daten lassen sich diese Geflechte (anderes Wort, weil Chart kein Netzwerk) aufzeigen.

## Magnus Hirschfeld

Magnus Hirschfeld gehört zu den prominentesten Personen der ersten Schwulenbewegung. Er war 1897 Mitgründer der ersten schwulen Interessensvertretung, dem Wissenschaftlich-humanitären Komitee, leitete das Institut für Sexualwissenschaft, das in , reiste für Vorträge um die Welt.

Doch es war nicht einfach: Schon 1921 wurde er in München von Nazis zusammengeschlagen, 1933 war das Institut für Sexualwissenschaft eines der ersten Ziele der Nazis nach der Machtübernahme. Sie haben es angezündet, es brannte nieder. Hirschfeld floh ins Ausland.

```{=html}
<iframe style="width: 80vw; height: 50vh; border: none;" src="https://database.factgrid.de/query/embed.html#%23defaultView%3AImageGrid%0A%0A%23%20Prefix%20standard%20%0A%23%20Factgrid%0APREFIX%20fg%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fentity%2F%3E%0APREFIX%20fgt%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fprop%2Fdirect%2F%3E%0A%23%20DBpedia%0APREFIX%20dbo%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%20%0APREFIX%20dbr%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%20%0A%23%20Wikidata%0APREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0A%23%20misc%0APREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX%20dct%3A%20%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20wikibase%3A%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0APREFIX%20bd%3A%20%3Chttp%3A%2F%2Fwww.bigdata.com%2Frdf%23%3E%0APREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0Aprefix%20foaf%3A%20%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%20%0A%20%20%20%20%0ASELECT%20DISTINCT%20%3Fdb_wikilink%20%3Fimage%20where%20%7B%0A%0A%20%20%23%20labels%20from%20Factgrid%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%20%20%0A%20%20%0A%20%20%23%20starting%20point%20is%20a%20factgrid%20item%0A%20%20BIND%28fg%3AQ225307%20as%20%3Ffg_item%29%0A%20%20%23%20transform%20wikidata%20qid%20in%20factgrid%20to%20wikidata%20entity%20iri%0A%20%20%3Flink%20schema%3Aabout%20%3Ffg_item%20.%0A%20%20%3Flink%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fwww.wikidata.org%2F%3E%20.%20%0A%20%20%3Flink%20schema%3Aname%20%3Fqid.%0A%20%20BIND%28IRI%28CONCAT%28STR%28wd%3A%29%2C%20%3Fqid%29%29%20AS%20%3Fwd_item%29%0A%0A%20%20%23%20fetch%20data%20from%20DBpedia%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fdbpedia.org%2Fsparql%3E%20%7B%0A%20%20%20%20%23%20get%20Wikidata%20QID%20from%20DBPedia%20resource%0A%20%20%20%20%3Fdb_item%20owl%3AsameAs%20%3Fwd_item%0A%0A%20%20%20%20%23%20Links%20from%20Hirschfeld%27s%20Wikipedia%20Page%20to%20other%20Wikipedia%20pages%20of%20humans%0A%20%20%20%20%23%20also%20get%20the%20Wikidata%20QIDs%20of%20those%20linked%20humans%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%23%20get%20all%20wikipedia%20links%0A%20%20%20%20%20%20%3Fdb_item%20dbo%3AwikiPageWikiLink%20%3Fdb_wikilink%20.%0A%20%20%20%20%20%20%23%20just%20those%20that%20are%20persons%0A%20%20%20%20%20%20%3Fdb_wikilink%20a%20dbo%3APerson%20.%0A%20%20%20%20%20%20%23%20remove%20Stefan%20Zweig%2C%20because%20there%20is%20some%20data%20fuckup%20within%20that%20resource%20%28I%20informed%20DBpedia%29%0A%20%20%20%20%20%20MINUS%20%7B%0A%20%20%20%20%20%20%20%20%20FILTER%28REGEX%28STR%28%3Fdb_wikilink%29%2C%20%22Stefan_Zweig%7CLGBT_rights_by_country_or_territory%22%29%29%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%23%20also%20get%20their%20wikidata%20qid%27s%0A%20%20%20%20%20%20%3Fdb_wikilink%20owl%3AsameAs%20%3Fdb_wikilink_wd_item%20FILTER%28regex%28str%28%3Fdb_wikilink_wd_item%29%2C%20%22wikidata%22%20%29%29%0A%20%20%20%20%20%20%23%20add%20thumbnail%20image%0A%20%20%20%20%20%20%3Fdb_wikilink%20dbo%3Athumbnail%20%3Fimage%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20%23%20fetch%20data%20from%20wikidata%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E%20%7B%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%7D%0A%20%20%7D%0A%7D" referrerpolicy="origin" sandbox="allow-scripts allow-same-origin allow-popups" ></iframe>
```
## Anita Augspurg

```{=html}
<iframe style="width: 80vw; height: 50vh; border: none;" src="https://database.factgrid.de/query/embed.html#%23defaultView%3AImageGrid%0A%0A%23%20Prefix%20standard%20%0A%23%20Factgrid%0APREFIX%20fg%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fentity%2F%3E%0APREFIX%20fgt%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fprop%2Fdirect%2F%3E%0A%23%20DBpedia%0APREFIX%20dbo%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%20%0APREFIX%20dbr%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%20%0A%23%20Wikidata%0APREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0A%23%20misc%0APREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX%20dct%3A%20%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20wikibase%3A%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0APREFIX%20bd%3A%20%3Chttp%3A%2F%2Fwww.bigdata.com%2Frdf%23%3E%0APREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0Aprefix%20foaf%3A%20%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%20%0A%20%20%20%20%0ASELECT%20DISTINCT%20%3Ffg_item%20%3Flabel%20%3Fimage%20WHERE%20%7B%0A%0A%20%20%23%20labels%20from%20Factgrid%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%20%20%0A%20%20%0A%20%20%23%20starting%20point%20is%20a%20factgrid%20item%0A%20%20BIND%28fg%3AQ223420%20as%20%3Ffg_item%29%0A%20%20%23%20transform%20wikidata%20qid%20in%20factgrid%20to%20wikidata%20entity%20iri%0A%20%20%3Flink%20schema%3Aabout%20%3Ffg_item%20.%0A%20%20%3Flink%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fwww.wikidata.org%2F%3E%20.%20%0A%20%20%3Flink%20schema%3Aname%20%3Fqid.%0A%20%20BIND%28IRI%28CONCAT%28STR%28wd%3A%29%2C%20%3Fqid%29%29%20AS%20%3Fwd_item%29%0A%0A%20%20%7B%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20VALUES%20%3Frelations_fg%20%7B%0A%20%20%20%20%20%20%20%20%23%20see%20list%3A%20https%3A%2F%2Ftinyurl.com%2F268grhz2%0A%20%20%20%20%20%20%20%20fgt%3AP84%20%23%20spouse%0A%20%20%20%20%20%20%20%20fgt%3AP117%20%23%20unmarried%20partner%0A%20%20%20%20%20%20%20%20fgt%3AP117%20%23affair%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%3Ffg_item%20%3Frelations_fg%20%3Fvalue%20.%0A%20%20%20%20%20%20%20%20%3Fvalue%20fgt%3AP189%20%3Fimage%0A%20%20%20%20%20%20%20%20%0A%0A%20%20%20%20%7D%0A%20%20%7D%20UNION%20%7B%0A%20%20%23%20fetch%20data%20from%20DBpedia%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fdbpedia.org%2Fsparql%3E%20%7B%0A%20%20%20%20%23%20get%20Wikidata%20QID%20from%20DBPedia%20resource%0A%20%20%20%20%3Fdb_item%20owl%3AsameAs%20%3Fwd_item%0A%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20VALUES%20%3Frelations_db%20%7B%0A%20%20%20%20%20%20%20%20%23%20see%20list%3A%20https%3A%2F%2Fdbpedia.org%2Fontology%2FPerson%0A%20%20%20%20%20%20%20%20dbo%3Apartner%0A%20%20%20%20%20%20%20%20dbo%3Arelation%0A%20%20%20%20%20%20%20%20dbo%3Arelative%0A%20%20%20%20%20%20%20%20dbo%3Achild%0A%20%20%20%20%20%20%20%20dbo%3Aspouse%0A%20%20%20%20%20%20%20%20dbo%3Aparent%0A%20%20%20%20%20%20%20%20dbo%3Aopponent%0A%20%20%20%20%20%20%20%20dbo%3Aaffair%0A%20%20%20%20%20%20%20%20dbo%3Acolleague%0A%20%20%20%20%20%20%20%20dbo%3Afriend%0A%20%20%20%20%20%20%20%20dbo%3Asibling%0A%20%20%20%20%20%20%20%20dbo%3AspouseName%0A%20%20%20%20%20%20%20%20dbo%3Astudent%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%3Fdb_item%20%3Frelations_db%20%3Fvalue%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%0A%20%20%20%20%20%20%23%20get%20images%0A%20%20%20%20%20%20%7B%3Fvalue%20dbo%3Athumbnail%20%3Fimage%20.%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%20UNION%20%7B%0A%20%20%23%20fetch%20data%20from%20DBpedia%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fdbpedia.org%2Fsparql%3E%20%7B%0A%20%20%20%20%23%20get%20Wikidata%20QID%20from%20DBPedia%20resource%0A%20%20%20%20%3Fdb_item%20owl%3AsameAs%20%3Fwd_item%0A%0A%20%20%20%20OPTIONAL%20%7B%20%0A%20%20%20%20%20%20%23%20get%20all%20wikipedia%20links%0A%20%20%20%20%20%20%3Fdb_item%20dbo%3AwikiPageWikiLink%20%3Fdb_wikilink%20.%0A%20%20%20%20%20%20%23%20just%20those%20that%20are%20persons%0A%20%20%20%20%20%20%3Fdb_wikilink%20a%20dbo%3APerson%20.%0A%20%20%20%20%20%20%23%20remove%20Stefan%20Zweig%2C%20because%20there%20is%20some%20data%20fuckup%20within%20that%20resource%20%28I%20informed%20DBpedia%29%0A%20%20%20%20%20%20MINUS%20%7BFILTER%28REGEX%28STR%28%3Fdb_wikilink%29%2C%20%22Stefan_Zweig%7CLGBT_rights_by_country_or_territory%22%29%29%7D%0A%20%20%20%20%20%20%23%20also%20get%20their%20wikidata%20qid%27s%0A%20%20%20%20%20%20%3Fdb_wikilink%20owl%3AsameAs%20%3Fdb_wikilink_wd_item%20FILTER%28regex%28str%28%3Fdb_wikilink_wd_item%29%2C%20%22wikidata%22%20%29%29%0A%0A%20%20%20%20%3Fdb_wikilink%20dbo%3Athumbnail%20%3Fimage%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%0A%7D%20UNION%20%7B%0A%20%20%23%20fetch%20data%20from%20wikidata%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E%20%7B%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20VALUES%20%3Frelations_wd%20%7B%0A%20%20%20%20%20%20%20%20%23%20see%20list%3A%20https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FWikidata%3AList_of_properties%2FWikidata_property_for_items_about_people_or_organisations%2Fhuman%0A%20%20%20%20%20%20%20%20wdt%3AP26%20%23%20spouse%0A%20%20%20%20%20%20%20%20wdt%3AP22%20%23%20father%0A%20%20%20%20%20%20%20%20wdt%3AP25%20%23%20mother%0A%20%20%20%20%20%20%20%20wdt%3AP40%20%23%20child%0A%20%20%20%20%20%20%20%20wdt%3AP451%20%23%20unmarried%20partner%0A%20%20%20%20%20%20%20%20wdt%3AP1038%20%23%20relative%0A%20%20%20%20%20%20%20%20wdt%3AP1066%20%23%20student%20of%0A%20%20%20%20%20%20%20%20wdt%3AP1290%20%23%20godparent%0A%20%20%20%20%20%20%20%20wdt%3AP3373%20%23%20sibling%0A%20%20%20%20%20%20%20%20wdt%3AP3448%20%23%20stepparent%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%3Fwd_item%20%3Frelations_wd%20%3Fvalue.%0A%20%20%20%20%23%3Fproperty%20wikibase%3AdirectClaim%20%3Frelations.%0A%20%20%20%20%3Fvalue%20wdt%3AP18%20%3Fimage%0A%20%20%20%7D%0A%20%20%20%7D%0A%20%20%7D%0A%20%20%23%20generate%20label%20from%20cascade%0A%20BIND%28COALESCE%28%3FvalueLabel%2C%20%3Fvalue%2C%20%3Fdb_wikilink%20%2C%20%22no_label%22%29%20AS%20%3Flabel%29.%0A%7D%20" referrerpolicy="origin" sandbox="allow-scripts allow-same-origin allow-popups" ></iframe>
```
## Erika Mann

```{=html}
<iframe style="width: 80vw; height: 50vh; border: none;" src="https://database.factgrid.de/query/embed.html#%23defaultView%3AImageGrid%0A%0A%23%20Prefix%20standard%20%0A%23%20Factgrid%0APREFIX%20fg%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fentity%2F%3E%0APREFIX%20fgt%3A%20%3Chttps%3A%2F%2Fdatabase.factgrid.de%2Fprop%2Fdirect%2F%3E%0A%23%20DBpedia%0APREFIX%20dbo%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2F%3E%20%0APREFIX%20dbr%3A%20%3Chttp%3A%2F%2Fdbpedia.org%2Fresource%2F%3E%20%0A%23%20Wikidata%0APREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0A%23%20misc%0APREFIX%20owl%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0APREFIX%20dct%3A%20%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20wikibase%3A%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0APREFIX%20bd%3A%20%3Chttp%3A%2F%2Fwww.bigdata.com%2Frdf%23%3E%0APREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0Aprefix%20foaf%3A%20%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%20%0A%20%20%20%20%0ASELECT%20DISTINCT%20%3Ffg_item%20%3Flabel%20%3Fimage%20WHERE%20%7B%0A%0A%20%20%23%20labels%20from%20Factgrid%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%20%20%0A%20%20%0A%20%20%23%20starting%20point%20is%20a%20factgrid%20item%0A%20%20BIND%28fg%3AQ226350%20as%20%3Ffg_item%29%0A%20%20%23%20transform%20wikidata%20qid%20in%20factgrid%20to%20wikidata%20entity%20iri%0A%20%20%3Flink%20schema%3Aabout%20%3Ffg_item%20.%0A%20%20%3Flink%20schema%3AisPartOf%20%3Chttps%3A%2F%2Fwww.wikidata.org%2F%3E%20.%20%0A%20%20%3Flink%20schema%3Aname%20%3Fqid.%0A%20%20BIND%28IRI%28CONCAT%28STR%28wd%3A%29%2C%20%3Fqid%29%29%20AS%20%3Fwd_item%29%0A%0A%20%20%7B%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20VALUES%20%3Frelations_fg%20%7B%0A%20%20%20%20%20%20%20%20%23%20see%20list%3A%20https%3A%2F%2Ftinyurl.com%2F268grhz2%0A%20%20%20%20%20%20%20%20fgt%3AP84%20%23%20spouse%0A%20%20%20%20%20%20%20%20fgt%3AP117%20%23%20unmarried%20partner%0A%20%20%20%20%20%20%20%20fgt%3AP117%20%23affair%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%3Ffg_item%20%3Frelations_fg%20%3Fvalue%20.%0A%20%20%20%20%20%20%20%20%3Fvalue%20fgt%3AP189%20%3Fimage%0A%20%20%20%20%20%20%20%20%0A%0A%20%20%20%20%7D%0A%20%20%7D%20UNION%20%7B%0A%20%20%23%20fetch%20data%20from%20DBpedia%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fdbpedia.org%2Fsparql%3E%20%7B%0A%20%20%20%20%23%20get%20Wikidata%20QID%20from%20DBPedia%20resource%0A%20%20%20%20%3Fdb_item%20owl%3AsameAs%20%3Fwd_item%0A%0A%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20VALUES%20%3Frelations_db%20%7B%0A%20%20%20%20%20%20%20%20%23%20see%20list%3A%20https%3A%2F%2Fdbpedia.org%2Fontology%2FPerson%0A%20%20%20%20%20%20%20%20dbo%3Apartner%0A%20%20%20%20%20%20%20%20dbo%3Arelation%0A%20%20%20%20%20%20%20%20dbo%3Arelative%0A%20%20%20%20%20%20%20%20dbo%3Achild%0A%20%20%20%20%20%20%20%20dbo%3Aspouse%0A%20%20%20%20%20%20%20%20dbo%3Aparent%0A%20%20%20%20%20%20%20%20dbo%3Aopponent%0A%20%20%20%20%20%20%20%20dbo%3Aaffair%0A%20%20%20%20%20%20%20%20dbo%3Acolleague%0A%20%20%20%20%20%20%20%20dbo%3Afriend%0A%20%20%20%20%20%20%20%20dbo%3Asibling%0A%20%20%20%20%20%20%20%20dbo%3AspouseName%0A%20%20%20%20%20%20%20%20dbo%3Astudent%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%3Fdb_item%20%3Frelations_db%20%3Fvalue%20.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%0A%20%20%20%20%20%20%23%20get%20images%0A%20%20%20%20%20%20%7B%3Fvalue%20dbo%3Athumbnail%20%3Fimage%20.%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%20UNION%20%7B%0A%20%20%23%20fetch%20data%20from%20DBpedia%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fdbpedia.org%2Fsparql%3E%20%7B%0A%20%20%20%20%23%20get%20Wikidata%20QID%20from%20DBPedia%20resource%0A%20%20%20%20%3Fdb_item%20owl%3AsameAs%20%3Fwd_item%0A%0A%20%20%20%20OPTIONAL%20%7B%20%0A%20%20%20%20%20%20%23%20get%20all%20wikipedia%20links%0A%20%20%20%20%20%20%3Fdb_item%20dbo%3AwikiPageWikiLink%20%3Fdb_wikilink%20.%0A%20%20%20%20%20%20%23%20just%20those%20that%20are%20persons%0A%20%20%20%20%20%20%3Fdb_wikilink%20a%20dbo%3APerson%20.%0A%20%20%20%20%20%20%23%20remove%20Stefan%20Zweig%2C%20because%20there%20is%20some%20data%20fuckup%20within%20that%20resource%20%28I%20informed%20DBpedia%29%0A%20%20%20%20%20%20MINUS%20%7BFILTER%28REGEX%28STR%28%3Fdb_wikilink%29%2C%20%22Stefan_Zweig%7CLGBT_rights_by_country_or_territory%22%29%29%7D%0A%20%20%20%20%20%20%23%20also%20get%20their%20wikidata%20qid%27s%0A%20%20%20%20%20%20%3Fdb_wikilink%20owl%3AsameAs%20%3Fdb_wikilink_wd_item%20FILTER%28regex%28str%28%3Fdb_wikilink_wd_item%29%2C%20%22wikidata%22%20%29%29%0A%0A%20%20%20%20%3Fdb_wikilink%20dbo%3Athumbnail%20%3Fimage%7D%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%0A%7D%20UNION%20%7B%0A%20%20%23%20fetch%20data%20from%20wikidata%0A%20%20SERVICE%20%3Chttps%3A%2F%2Fquery.wikidata.org%2Fsparql%3E%20%7B%0A%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20VALUES%20%3Frelations_wd%20%7B%0A%20%20%20%20%20%20%20%20%23%20see%20list%3A%20https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FWikidata%3AList_of_properties%2FWikidata_property_for_items_about_people_or_organisations%2Fhuman%0A%20%20%20%20%20%20%20%20wdt%3AP26%20%23%20spouse%0A%20%20%20%20%20%20%20%20wdt%3AP22%20%23%20father%0A%20%20%20%20%20%20%20%20wdt%3AP25%20%23%20mother%0A%20%20%20%20%20%20%20%20wdt%3AP40%20%23%20child%0A%20%20%20%20%20%20%20%20wdt%3AP451%20%23%20unmarried%20partner%0A%20%20%20%20%20%20%20%20wdt%3AP1038%20%23%20relative%0A%20%20%20%20%20%20%20%20wdt%3AP1066%20%23%20student%20of%0A%20%20%20%20%20%20%20%20wdt%3AP1290%20%23%20godparent%0A%20%20%20%20%20%20%20%20wdt%3AP3373%20%23%20sibling%0A%20%20%20%20%20%20%20%20wdt%3AP3448%20%23%20stepparent%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%3Fwd_item%20%3Frelations_wd%20%3Fvalue.%0A%20%20%20%20%23%3Fproperty%20wikibase%3AdirectClaim%20%3Frelations.%0A%20%20%20%20%3Fvalue%20wdt%3AP18%20%3Fimage%0A%20%20%20%7D%0A%20%20%20%7D%0A%20%20%7D%0A%20%20%23%20generate%20label%20from%20cascade%0A%20BIND%28COALESCE%28%3FvalueLabel%2C%20%3Fvalue%2C%20%3Fdb_wikilink%20%2C%20%22no_label%22%29%20AS%20%3Flabel%29.%0A%7D%20" referrerpolicy="origin" sandbox="allow-scripts allow-same-origin allow-popups" ></iframe>
```
