---
title: "data modeling"
---

The linked data that I am mining in my Remove NA project will reside in Factgrid, a wikibase instance for historians.

So after I cleaned the data from various sources, I had to align my relational data to Factgrid's data model.

In this post, I'll share some insights during the process.

## On Sex and Gender

This is a tough one, when dealing with data on queer history. Because it's not just another data field, but the core of the movement and central point of personal identity.

For example the gender question.

Since I am working in the LGBTIQ\* sphere this a quite important question. Using automated gender detections is risky and may result in quite a lot of false positives or general misclassifications.

Factgrid has an implemented mechanism to get the sex or gender from a list of names. It remsembles other APIs that want to derive the gender from first names. It probably works well in many cases, but there are also seemingly infinite pitfalls:

-   First names that aren't in the data
-   First names used across genders, think of `Kim`, `Sasha` etc.
-   How can a first name be determined in the first place? An easy one, right? Take the string up to the first space. Taking the string up to the first space is of course the obvious idea. Like most obvious ideas, it falls short.
-   What if data entry was not consistent and the last name comes first?

### Catharina Margaretha Linck

For example [Catharina Margaretha Linck](https://en.wikipedia.org/wiki/Catharina_Margaretha_Linck): Linck was the last person in Germany sentenced to death due to her sexual orientation as well as her appearance. Throughout her life, Linck has repeatedly changed her appearance: Sometimes she was under a male name and dress, sometimes as a woman. Was she a lesbian? Was she trans? We will never know.

But what we know is that we was definitly not strictly one or the other.

Linck's case is a good example of how the view of people like Linck is changing.

The author [Angela Steidele (German Wikipedia)](https://de.wikipedia.org/wiki/Angela_Steidele) has published two books about Linck. The first in 2004, the second almost 20 years later in 2021. In an [interview with queer.de](https://www.queer.de/detail.php?article_id=40408), Steidele tells us that she has come to interpret the sources primarily as evidence of lesbian desire.

> Trans people receive the life of Catharina Linck differently than I do. Although I see the lesbian in her as a lesbian, I have been more linguistically mindful that trans people legitimately recognize a trans person here. For this reason, I deliberately left it more open in the narrative style of the rewrite as to who he/she actually was. It was narrative intent that the change of gender also be reflected linguistically, and therefore I wrote of a man when Catharina Linck was recognizable to others as a man. Nevertheless, inconsistencies occur through quotations, so that between "he" and "she" the gender of the person appears as fluid. This fluidity opens up more room for interpretation and identification and also makes Linck a very modern figure.

In [Lincks Wikidata Items](https://www.wikidata.org/wiki/Q1050792) the sex and gender item says `transgender male`.

If she was a lesbian using male appearance to live her life or if he was trans we will never know for certain and is part of interpretation.

Admittedly, this case is outstandingly complicated, but it illustrates the issue well.

### My procedure

My decision was to fetch the `sex or gender` information from Wikidata if I have the external ID for an entity.

The rest was manually assigned.

I know, that this might produces some false positives.

### Factgrid Data Modeling!


[](images/paste-478B4FA0.png)

<iframe style="width: 80vw; height: 50vh; border: none;" src="https://database.factgrid.de/query/embed.html#SELECT%20%3FGeschlechtsidentit_t%20%3FGeschlechtsidentit_tLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%20%20%3FGeschlechtsidentit_t%20wdt%3AP2%20wd%3AQ402121.%0A%7D%0ALIMIT%20100" referrerpolicy="origin" sandbox="allow-scripts allow-same-origin allow-popups" ></iframe>




