---
title: "Remove NA"
subtitle: "Strukturierte Daten zur queeren Geschichte"
execute:
  echo: false
  message: false
  warning: false
---

Remove NA fasst Daten zur LGBTIQ*-Geschichte in einer einheitlichen Datenbank zusammen, um sie leichter zugänglich und nützlicher zu machen. Mehr darüber, warum wir Remove NA aufbauen. 

## Erkunde die Daten


<div class="alert alert-primary">
  <strong>Die Weggefährten von Magnus Hirschfeld</strong>
</div>

<div class="alert alert-secondary">
  <strong>Chronik queerer Geschichte</strong> mit Fokus auf München
</div>


<div class="alert alert-info">
  <strong>Autonome Frauenbewegung</strong>
</div>

<div class="alert alert-success">
  <strong>Beziehungsgeflecht:</strong> Welche Personen waren in welchen Organisationen aktiv?
</div>

## Warum braucht es dieses Projekt?

Daten, Informationen und Wissen zur queeren Geschichte sollten existieren. 
Nur so kann queere Geschichte in den komplexeren, datenbasierten Algorithmen sichtbar werden, die zunehmend Teil unseres Alltags sind.
Das Projekt Remove NA sammelt, integriert und veröffentlicht Daten zur LGBTIQ*-Geschichte.
Fokus ist dabei München, geht aber auch darüber hinaus.


## NAs removed

```{r}
config_file <- "static/config.yml"
config <- yaml::read_yaml(config_file)

na_removed_wikidata <- nrow(readr::read_delim(url(config$revisions_github)))
```


```{=html}
<div class="card bg-light mb-3" style="max-width: 20rem;">
  <div class="card-header bg-light">Wikidata</div>
  <div class="card-body">
    <h2 class="card-title">`r as.character(na_removed_wikidata)`</h2>
    <p class="card-text">Lücken zur queeren Geschichte in <strong>Wikidata</strong> entfernt.</p>
  </div>
   <div class="card-footer text-muted bg-light">
    Stand: `r Sys.Date()`
  </div>
</div>

```
---
